version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: id17622113_id16359616_sensor
      MYSQL_USER: id17622113_id16359616_root
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'

volumes:
  db_data: {}

